spring.application.name=webpay

server.port=9696

#MYSQL
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.datasource.url=jdbc:h2:file:/data/demo
spring.jpa.hibernate.ddl-auto=update
spring.datasource.hikari.connection-timeout=18000
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.maximum-pool-size=200
spring.datasource.hikari.max-lifetime=10000
spring.jpa.properties.hibernate.jdbc.batch_size=5
spring.datasource.hikari.validationTimeout=18000
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
spring.jackson.time-zone=Africa/Lagos
management.endpoint.metrics.enabled= true
spring.jmx.enabled= false


#INTERSWITCH WEBPAY
ISW_PURCHASEURL=https://qa.interswitchng.com/api/v3/purchases
ISW_AUTHVERIFYURL=https://qa.interswitchng.com/api/v3/purchases/otps/auths
ISW_AUTHURL=https://apps.qa.interswitchng.com/passport/oauth/token?grant_type=client_credentials
ISW_STATUSCHECKURL=https://qa.interswitchng.com/collections/api/v1/gettransaction.json?merchantcode=MX165929&transactionreference=
ISW_RESENDOTPURL=https://qa.interswitchng.com/api/v3/purchases/otps/resend
ISW_BASICAUTH=
ISW_USERNAME=
ISW_PASSWORD=
ISW_CLIENTID=
ISW_SECRETKEY=
MERCHANT_CODE=
PAYMENT_ITEM_ID=
ISW_MODULUS=9c7b3ba621a26c4b02f48cfc07ef6ee0aed8e12b4bd11c5cc0abf80d5206be69e1891e60fc88e2d565e2fabe4d0cf630e318a6c721c3ded718d0c530cdf050387ad0a30a336899bbda877d0ec7c7c3ffe693988bfae0ffbab71b25468c7814924f022cb5fda36e0d2c30a7161fa1c6fb5fbd7d05adbef7e68d48f8b6c5f511827c4b1c5ed15b6f20555affc4d0857ef7ab2b5c18ba22bea5d3a79bd1834badb5878d8c7a4b19da20c1f62340b1f7fbf01d2f2e97c9714a9df376ac0ea58072b2b77aeb7872b54a89667519de44d0fc73540beeaec4cb778a45eebfbefe2d817a8a8319b2bc6d9fa714f5289ec7c0dbc43496d71cf2a642cb679b0fc4072fd2cf
ISW_PUBLIC_EXPONENT=010001
logging.level.web=DEBUG
spring.mvc.log-request-details=true


#LOGGING
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
spring.output.ansi.enabled=detect
logging.logback.rollingpolicy.max-file-size=10MB
logging.file.path=${user.home}/webpaylogs


#API DOC
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
